version: '3.8'

services:
  client:
    image: choremate-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    deploy:
      replicas: 1
    depends_on:
      - server

  server:
    image: choremate-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: rolling-update
    environment:
      NODE_ENV: production
      PORT: 8000
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_URI: ${MONGODB_URI}
    secrets:
      - mongodb_password

secrets:
  mongodb_password:
    external: true